AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EV Charging Station Management System - SAM Template

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 256
    Environment:
      Variables:
        STATIONS_TABLE: !Ref StationsTable
        SESSIONS_TABLE: !Ref SessionsTable
        USERS_TABLE: !Ref UsersTable
        ERROR_LOGS_TABLE: !Ref ErrorLogsTable
        AWS_REGION_NAME: !Ref AWS::Region

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
  CognitoDomain:
    Type: String
    Default: ev-charging-station

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Resources:

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ev-charging-users-${Environment}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: name
          Required: true
          Mutable: true
        - Name: phone_number
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ev-charging-client-${Environment}
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${CognitoDomain}-${Environment}
      UserPoolId: !Ref UserPool

  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: ADMIN
      UserPoolId: !Ref UserPool
      Description: System administrators
      Precedence: 0

  TechSupportGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: TECH_SUPPORT
      UserPoolId: !Ref UserPool
      Description: Technical support staff
      Precedence: 1

  UserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: USER
      UserPoolId: !Ref UserPool
      Description: Regular charging station users
      Precedence: 2

  StationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Stations-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: stationId
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: stationId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Sessions-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: updatedAt
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: updatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Users-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  ErrorLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ErrorLogs-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: level
          AttributeType: S
        - AttributeName: service
          AttributeType: S
        - AttributeName: logStatus
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: level-index
          KeySchema:
            - AttributeName: level
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: service-index
          KeySchema:
            - AttributeName: service
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status-index
          KeySchema:
            - AttributeName: logStatus
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ChargingSimulatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ev-charging-simulator-${Environment}
      CodeUri: ../lambdas/charging_simulator/
      Handler: handler.lambda_handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref StationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ErrorLogsTable
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Description: Simulate charging ticks
            Enabled: true

  StationServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ev-station-service-${Environment}
      CodeUri: ../lambdas/station_service/
      Handler: handler.lambda_handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ErrorLogsTable

  SessionServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ev-session-service-${Environment}
      CodeUri: ../lambdas/session_service/
      Handler: handler.lambda_handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref StationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ErrorLogsTable

  NotificationServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ev-notification-service-${Environment}
      CodeUri: ../lambdas/notification_service/
      Handler: handler.lambda_handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ErrorLogsTable

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ev-health-check-${Environment}
      CodeUri: ../lambdas/health_check/
      Handler: handler.lambda_handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref StationsTable
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ev-charging-shared-${Environment}
      ContentUri: ../lambdas/shared/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId
  StationsTableName:
    Value: !Ref StationsTable
  SessionsTableName:
    Value: !Ref SessionsTable
  UsersTableName:
    Value: !Ref UsersTable
  ErrorLogsTableName:
    Value: !Ref ErrorLogsTable
  HealthCheckFunctionArn:
    Value: !GetAtt HealthCheckFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-HealthCheckFunctionArn
